name: CI/CD with Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          
      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app:latest myrepo/my-app:latest
          docker push myrepo/my-app:latest

      - name: Update Kubernetes manifest in infra-repo
        run: |
          git clone https://github.com/ton-org/infra-repo.git
          cd infra-repo
          sed -i 's|image: myrepo/my-app:.*|image: myrepo/my-app:latest|' k8s/deployment.yaml
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update image version to latest"
          git push
